/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package br.com.example.broker.producer;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TesteObj extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5828607308121097474L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TesteObj\",\"namespace\":\"br.com.example.broker.producer\",\"fields\":[{\"name\":\"Name\",\"type\":\"string\",\"avro.java.string\":\"String\"}],\"version\":\"1.0.0\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TesteObj> ENCODER =
      new BinaryMessageEncoder<TesteObj>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TesteObj> DECODER =
      new BinaryMessageDecoder<TesteObj>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TesteObj> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TesteObj> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TesteObj>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TesteObj to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TesteObj from a ByteBuffer. */
  public static TesteObj fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TesteObj() {}

  /**
   * All-args constructor.
   * @param Name The new value for Name
   */
  public TesteObj(java.lang.CharSequence Name) {
    this.Name = Name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Name = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Creates a new TesteObj RecordBuilder.
   * @return A new TesteObj RecordBuilder
   */
  public static br.com.example.broker.producer.TesteObj.Builder newBuilder() {
    return new br.com.example.broker.producer.TesteObj.Builder();
  }

  /**
   * Creates a new TesteObj RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TesteObj RecordBuilder
   */
  public static br.com.example.broker.producer.TesteObj.Builder newBuilder(br.com.example.broker.producer.TesteObj.Builder other) {
    return new br.com.example.broker.producer.TesteObj.Builder(other);
  }

  /**
   * Creates a new TesteObj RecordBuilder by copying an existing TesteObj instance.
   * @param other The existing instance to copy.
   * @return A new TesteObj RecordBuilder
   */
  public static br.com.example.broker.producer.TesteObj.Builder newBuilder(br.com.example.broker.producer.TesteObj other) {
    return new br.com.example.broker.producer.TesteObj.Builder(other);
  }

  /**
   * RecordBuilder for TesteObj instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TesteObj>
    implements org.apache.avro.data.RecordBuilder<TesteObj> {

    private java.lang.CharSequence Name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(br.com.example.broker.producer.TesteObj.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TesteObj instance
     * @param other The existing instance to copy.
     */
    private Builder(br.com.example.broker.producer.TesteObj other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Name)) {
        this.Name = data().deepCopy(fields()[0].schema(), other.Name);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public br.com.example.broker.producer.TesteObj.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public br.com.example.broker.producer.TesteObj.Builder clearName() {
      Name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TesteObj build() {
      try {
        TesteObj record = new TesteObj();
        record.Name = fieldSetFlags()[0] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TesteObj>
    WRITER$ = (org.apache.avro.io.DatumWriter<TesteObj>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TesteObj>
    READER$ = (org.apache.avro.io.DatumReader<TesteObj>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
